In [1]:
import sys
import numpy as np
import os
from scipy import io

In [2]:
def onefile(mat_t):
  m_data = []
  num = len(mat_t)-len(mat_t)%3
  #num = len(mat_t)
  for i in range(0,num,1):
    onetime=[]
    for j in range(0,20,1):
      onetime.append([mat_t[i,0,j],mat_t[i,1,j],mat_t[i,2,j]])
    m_data.append(onetime)

  # m_data = np.array(m_data)   
  # print(m_data.shape)
  # print(m_data[0:2,:,:])
  return m_data

def label_maker(name,mat_t):
  new_label = []
  num = len(mat_t)-len(mat_t)%3
  num=num/3
  #num = len(mat_t)
  for i in range(0,int(num),1):
        new_label.append(name.split('_')[0])
  return new_label

In [9]:
data = [] 
label = []
datafilename = r'H:/LI project/3d sk detect/UTD-MHAD/UTD-MHAD_skeleton/a1_s2_t1_skeleton.mat'
mat = io.loadmat(datafilename)
mat_t = np.transpose(mat['d_skel'])
data = data + (onefile(mat_t))
label = label+label_maker('a1_s2_t1_skeleton.mat',mat_t)
data = np.array(data)
label = np.array(label)
data = data.reshape(-1,3,20,3)
print(data.shape)
print(data[0:2])
print(label.shape)
print(label[0:2])

(19, 3, 20, 3)
[[[[-9.02134478e-02  3.66664082e-01  2.86699033e+00]
   [-7.97464848e-02  1.82575300e-01  2.88687849e+00]
   [-7.37292469e-02 -1.59673482e-01  2.90217447e+00]
   [-6.74642175e-02 -2.21902549e-01  2.85435128e+00]
   [-2.26700976e-01  6.40372261e-02  2.87106729e+00]
   [-2.66580820e-01 -1.83556408e-01  2.85524988e+00]
   [-2.59252012e-01 -4.03864741e-01  2.81703496e+00]
   [-2.64122725e-01 -4.47912306e-01  2.81338596e+00]
   [ 7.88560957e-02  7.90701956e-02  2.90052748e+00]
   [ 1.30936891e-01 -1.85234785e-01  2.89193344e+00]
   [ 1.46790326e-01 -4.01827246e-01  2.83431959e+00]
   [ 1.42292276e-01 -4.46076155e-01  2.83205414e+00]
   [-1.34378001e-01 -2.94132978e-01  2.83662343e+00]
   [-1.22406110e-01 -6.96252525e-01  2.93441534e+00]
   [-1.01907231e-01 -1.00724363e+00  2.93264890e+00]
   [-1.24732532e-01 -1.06912231e+00  2.88628531e+00]
   [ 3.77594843e-03 -2.88255900e-01  2.85638380e+00]
   [-2.93504819e-03 -7.00554729e-01  2.94177604e+00]
   [-2.94753704e-02 -1.00776935

In [3]:
trainX = []
trainY =[]
testX = []
testY=[]
dataFile = r'H:/LI project/3d sk detect/UTD-MHAD/UTD-MHAD_skeleton/'
filename = os.listdir(dataFile)
for name in filename:
    print("----------------now is deal with  ",name," file")
    x = name.split("_")[1]
    if(x =="s1"or x=='s3'or x=='s5' or x=='s7'):
        datafilename = dataFile+name
        mat = io.loadmat(datafilename)
        mat_t = np.transpose(mat['d_skel'])
        trainX = trainX + (onefile(mat_t))
        trainY = trainY+label_maker(name,mat_t)
    else:
        datafilename = dataFile+name
        mat = io.loadmat(datafilename)
        mat_t = np.transpose(mat['d_skel'])
        testX = testX + (onefile(mat_t))
        testY = testY+label_maker(name,mat_t)
trainX = np.array(trainX)
trainY = np.array(trainY)
testX = np.array(testX)
testY = np.array(testY)

trainX = trainX.reshape(-1,3,20,3)
testX = testX.reshape(-1,3,20,3)
print('trainx',trainX.shape)
print('trainy',trainY.shape)
print('testx',testX.shape)
print('testy',testY.shape)

----------------now is deal with   a10_s1_t1_skeleton.mat  file
----------------now is deal with   a10_s1_t2_skeleton.mat  file
----------------now is deal with   a10_s1_t3_skeleton.mat  file
----------------now is deal with   a10_s1_t4_skeleton.mat  file
----------------now is deal with   a10_s2_t1_skeleton.mat  file
----------------now is deal with   a10_s2_t2_skeleton.mat  file
----------------now is deal with   a10_s2_t3_skeleton.mat  file
----------------now is deal with   a10_s2_t4_skeleton.mat  file
----------------now is deal with   a10_s3_t1_skeleton.mat  file
----------------now is deal with   a10_s3_t2_skeleton.mat  file
----------------now is deal with   a10_s3_t3_skeleton.mat  file
----------------now is deal with   a10_s3_t4_skeleton.mat  file
----------------now is deal with   a10_s4_t1_skeleton.mat  file
----------------now is deal with   a10_s4_t2_skeleton.mat  file
----------------now is deal with   a10_s4_t3_skeleton.mat  file
----------------now is deal with   a10_s

----------------now is deal with   a16_s6_t2_skeleton.mat  file
----------------now is deal with   a16_s6_t3_skeleton.mat  file
----------------now is deal with   a16_s6_t4_skeleton.mat  file
----------------now is deal with   a16_s7_t1_skeleton.mat  file
----------------now is deal with   a16_s7_t2_skeleton.mat  file
----------------now is deal with   a16_s7_t3_skeleton.mat  file
----------------now is deal with   a16_s7_t4_skeleton.mat  file
----------------now is deal with   a16_s8_t1_skeleton.mat  file
----------------now is deal with   a16_s8_t2_skeleton.mat  file
----------------now is deal with   a16_s8_t3_skeleton.mat  file
----------------now is deal with   a16_s8_t4_skeleton.mat  file
----------------now is deal with   a17_s1_t1_skeleton.mat  file
----------------now is deal with   a17_s1_t2_skeleton.mat  file
----------------now is deal with   a17_s1_t3_skeleton.mat  file
----------------now is deal with   a17_s1_t4_skeleton.mat  file
----------------now is deal with   a17_s

----------------now is deal with   a20_s1_t2_skeleton.mat  file
----------------now is deal with   a20_s1_t3_skeleton.mat  file
----------------now is deal with   a20_s1_t4_skeleton.mat  file
----------------now is deal with   a20_s2_t1_skeleton.mat  file
----------------now is deal with   a20_s2_t2_skeleton.mat  file
----------------now is deal with   a20_s2_t3_skeleton.mat  file
----------------now is deal with   a20_s2_t4_skeleton.mat  file
----------------now is deal with   a20_s3_t1_skeleton.mat  file
----------------now is deal with   a20_s3_t2_skeleton.mat  file
----------------now is deal with   a20_s3_t3_skeleton.mat  file
----------------now is deal with   a20_s3_t4_skeleton.mat  file
----------------now is deal with   a20_s4_t1_skeleton.mat  file
----------------now is deal with   a20_s4_t2_skeleton.mat  file
----------------now is deal with   a20_s4_t3_skeleton.mat  file
----------------now is deal with   a20_s4_t4_skeleton.mat  file
----------------now is deal with   a20_s

----------------now is deal with   a24_s5_t4_skeleton.mat  file
----------------now is deal with   a24_s6_t1_skeleton.mat  file
----------------now is deal with   a24_s6_t2_skeleton.mat  file
----------------now is deal with   a24_s6_t3_skeleton.mat  file
----------------now is deal with   a24_s6_t4_skeleton.mat  file
----------------now is deal with   a24_s7_t1_skeleton.mat  file
----------------now is deal with   a24_s7_t2_skeleton.mat  file
----------------now is deal with   a24_s7_t3_skeleton.mat  file
----------------now is deal with   a24_s7_t4_skeleton.mat  file
----------------now is deal with   a24_s8_t1_skeleton.mat  file
----------------now is deal with   a24_s8_t2_skeleton.mat  file
----------------now is deal with   a24_s8_t3_skeleton.mat  file
----------------now is deal with   a24_s8_t4_skeleton.mat  file
----------------now is deal with   a25_s1_t1_skeleton.mat  file
----------------now is deal with   a25_s1_t2_skeleton.mat  file
----------------now is deal with   a25_s

----------------now is deal with   a2_s6_t4_skeleton.mat  file
----------------now is deal with   a2_s7_t1_skeleton.mat  file
----------------now is deal with   a2_s7_t2_skeleton.mat  file
----------------now is deal with   a2_s7_t3_skeleton.mat  file
----------------now is deal with   a2_s7_t4_skeleton.mat  file
----------------now is deal with   a2_s8_t1_skeleton.mat  file
----------------now is deal with   a2_s8_t2_skeleton.mat  file
----------------now is deal with   a2_s8_t3_skeleton.mat  file
----------------now is deal with   a2_s8_t4_skeleton.mat  file
----------------now is deal with   a3_s1_t1_skeleton.mat  file
----------------now is deal with   a3_s1_t2_skeleton.mat  file
----------------now is deal with   a3_s1_t3_skeleton.mat  file
----------------now is deal with   a3_s1_t4_skeleton.mat  file
----------------now is deal with   a3_s2_t1_skeleton.mat  file
----------------now is deal with   a3_s2_t2_skeleton.mat  file
----------------now is deal with   a3_s2_t3_skeleton.ma

----------------now is deal with   a7_s2_t3_skeleton.mat  file
----------------now is deal with   a7_s2_t4_skeleton.mat  file
----------------now is deal with   a7_s3_t1_skeleton.mat  file
----------------now is deal with   a7_s3_t2_skeleton.mat  file
----------------now is deal with   a7_s3_t3_skeleton.mat  file
----------------now is deal with   a7_s3_t4_skeleton.mat  file
----------------now is deal with   a7_s4_t1_skeleton.mat  file
----------------now is deal with   a7_s4_t2_skeleton.mat  file
----------------now is deal with   a7_s4_t3_skeleton.mat  file
----------------now is deal with   a7_s4_t4_skeleton.mat  file
----------------now is deal with   a7_s5_t1_skeleton.mat  file
----------------now is deal with   a7_s5_t2_skeleton.mat  file
----------------now is deal with   a7_s5_t3_skeleton.mat  file
----------------now is deal with   a7_s5_t4_skeleton.mat  file
----------------now is deal with   a7_s6_t1_skeleton.mat  file
----------------now is deal with   a7_s6_t2_skeleton.ma

In [4]:
np.save('H:/LI project/3d sk detect/UTD-MHAD/sk_UTD_trainx.npy',trainX)

In [5]:
np.save('H:/LI project/3d sk detect/UTD-MHAD/sk_UTD_trainy.npy',trainY)

In [6]:
np.save('H:/LI project/3d sk detect/UTD-MHAD/sk_UTD_testx.npy',testX)

In [7]:
np.save('H:/LI project/3d sk detect/UTD-MHAD/sk_UTD_testy.npy',testY)